### ISSUE TITLE
Product Visualization (RF03) - implementation of the main page (home)(issue-07)

### ISSUE THREAD

**Issue by TharcioCBM** [TharcioCBM/WebShopping#12]

**Comment by Jose-Luan** [comment]
# Product Visualization (RF03) - implementation of the main page (home)
## Description:
Development and integration of components for the system's homepage.

## Status:
Implemented the main components and structure of the homepage.

## Main features:
-  Introduced the FeaturedBanner component to showcase highlighted products.
-  Implemented the Navbar with navigation and search options.
-  Added the FeaturedProductsCarousel to highlight selected items.
-  Developed the CategoryCard component for easier navigation among categories.
-  Included AdvertisingBanners for promotions and advertising content.

## Related commit: [1ce8f0ec2ed77b626169c1a5153a99a9f9f41dc5]
