### ISSUE TITLE
Product View (RF03) - front-end - create search/filter screens (issue-08)

### ISSUE THREAD

**Issue by TharcioCBM** [TharcioCBM/WebShopping#13]
feat: barra de pesquisas e filtros avançados de pesquisa

**Comment by Jose-Luan** [comment]
# Product View (RF03) - front-end - create search/filter screens (issue-08)
## Status:
Search bar implemented on the home page

## Related commit: [1ce8f0ec2ed77b626169c1a5153a99a9f9f41dc5]
