### ISSUE TITLE
User Registration (RF01) - functionality integration (issue-03)

### ISSUE THREAD

**Issue by TharcioCBM** [TharcioCBM/WebShopping#3]
integração do back-end com o front-end

**Comment by Jose-Luan** [comment]
# Login and Authentication (RF02) - functionality integration
## Description:
Implementation of registration logic and integration with API

## Status:
Implemented the registration logic to integrate with API

## Main features:
-  Adds input states for username, email and password in RegisterModal.
-  Implements the POST request for the registration route (/api/auth/register).
-  Adds error handling and feedback messages to the user in case of registration failure.
