### ISSUE TITLE
Login and Authentication (RF02) - creating the login screen (issue-04)

### ISSUE THREAD

**Issue by TharcioCBM** [TharcioCBM/WebShopping#6]

**Comment by Jose-Luan** [comment]
# Login and Authentication (RF02) - creation of the login screen
## Description:
Implementation of the user login screen following the project specifications, including fields for email and password, as well as an interaction button such as "Register".

## Status:
Registration screen created and integrated with the main page. Registration modal implemented with transition functionality to the registration modal.

## Main features:
- Registration modal with field validation.
- Transition between the login and registration modals via "Register" and "Sign in" links.
- Show/hide password icons in the password field.
- Integration with Google icon for authentication.
- Reuse of components such as Wrapper and close button.
# Related commit: [253ebb56c3a0a57d3436ac26f616b6c9d5e3931a]
