### ISSUE TITLE
Login and Authentication (RF02) - functionality integration (issue-06)

### ISSUE THREAD

**Issue by TharcioCBM** [TharcioCBM/WebShopping#8]

**Comment by Jose-Luan** [comment]
## Login and Authentication (RF02) - functionality integration
# Description:
Implementation of registration logic and integration with API

# Status:
Implemented the registration logic to integrate with API

# Main features:
-  Adds input states for username, email and password in RegisterModal.
-  Implements the POST request for the registration route (/api/auth/register).
-  Adds error handling and feedback messages to the user in case of registration failure.

**Comment by Jose-Luan** [comment]
# Login and Authentication (RF02) - functionality integration
## Description:
Implementation of registration logic and integration with API

## Status:
Implemented the registration logic to integrate with API

## Main features:
- Adds input states for username,password in LoginModal.
- Implements the POST request for the registration route (/api/auth/login).
- Adds error handling and feedback messages to the user in case of registration failure.
## Related commit: [af2b8ae8f272f74bb7271e7535926ea6d6e7bbea]
